import { DOC_SECTIONS, FAQ_CATEGORIES } from "@/lib/docs-content";
import { DOC_GUIDES } from "@/lib/docs-guides";
import guideContent from "@/lib/docs-guides-content.json";

export interface DocSearchResult {
  type: "article" | "guide" | "faq";
  title: string;
  /** Where this result lives in the app, e.g. "/settings/support#requisitions" or "/settings/support/purchase-orders-guide". */
  path: string;
  /** A short snippet of the matching text, for a quick preview before fetching the full guide. */
  excerpt: string;
}

const STOPWORDS = new Set([
  "a", "an", "the", "how", "do", "does", "is", "are", "i", "to", "for", "of", "in", "on",
  "what", "when", "where", "can", "with", "and", "or", "my", "it", "this", "that",
]);

function tokenize(query: string): string[] {
  return query
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length > 1 && !STOPWORDS.has(w));
}

function score(text: string, tokens: string[]): number {
  const lower = text.toLowerCase();
  return tokens.reduce((sum, t) => sum + (lower.includes(t) ? 1 : 0), 0);
}

function excerptAround(text: string, tokens: string[], radius = 160): string {
  const lower = text.toLowerCase();
  const idx = tokens.map((t) => lower.indexOf(t)).find((i) => i >= 0) ?? -1;
  if (idx < 0) return text.slice(0, radius * 2).trim() + (text.length > radius * 2 ? "…" : "");
  const start = Math.max(0, idx - radius);
  const end = Math.min(text.length, idx + radius);
  return (start > 0 ? "…" : "") + text.slice(start, end).trim() + (end < text.length ? "…" : "");
}

/**
 * Full-text search over both tiers of in-app help content: the short
 * Support articles (src/lib/docs-content.ts — structured step-by-step data)
 * and the long-form Docs guides (src/lib/docs-guides.ts for metadata,
 * src/lib/docs-guides-content.json for body text — generated by
 * scripts/build-docs-index.mjs since guide pages are freeform JSX, not
 * structured data; re-run that script after editing a guide).
 *
 * Simple token-overlap scoring, not embeddings — good enough for a docs
 * corpus this size, and avoids an external dependency/API call from the MCP
 * route.
 */
export function searchDocs(query: string, limit = 5): DocSearchResult[] {
  const tokens = tokenize(query);
  if (tokens.length === 0) return [];

  const results: (DocSearchResult & { score: number })[] = [];

  for (const section of DOC_SECTIONS) {
    for (const article of section.articles) {
      const stepsText = article.steps.map((s) => `${s.step} ${s.detail}`).join(" ");
      const fullText = `${article.title} ${article.summary} ${stepsText}`;
      const s = score(article.title, tokens) * 3 + score(article.summary, tokens) * 2 + score(stepsText, tokens);
      if (s > 0) {
        results.push({
          type: "article",
          title: article.title,
          path: `/settings/support#${section.id}:${article.id}`,
          excerpt: excerptAround(fullText, tokens),
          score: s,
        });
      }
    }
  }

  for (const guide of DOC_GUIDES) {
    const body = (guideContent as Record<string, string>)[guide.slug] ?? "";
    const fullText = `${guide.title} ${guide.description} ${body}`;
    const s = score(guide.title, tokens) * 3 + score(guide.description, tokens) * 2 + score(body, tokens);
    if (s > 0) {
      results.push({
        type: "guide",
        title: guide.title,
        path: `/settings/support/${guide.slug}`,
        excerpt: excerptAround(body || fullText, tokens),
        score: s,
      });
    }
  }

  for (const category of FAQ_CATEGORIES) {
    for (const faq of category.items) {
      const fullText = `${faq.q} ${faq.a}`;
      const s = score(faq.q, tokens) * 3 + score(faq.a, tokens);
      if (s > 0) {
        results.push({
          type: "faq",
          title: faq.q,
          path: `/settings/support#faq`,
          excerpt: excerptAround(faq.a, tokens),
          score: s,
        });
      }
    }
  }

  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ score: _score, ...r }) => r);
}

/** Full body text of one long-form guide, for a get_guide follow-up after search_docs points at it. */
export function getGuideContent(slug: string): { title: string; description: string; content: string } | null {
  const guide = DOC_GUIDES.find((g) => g.slug === slug);
  if (!guide) return null;
  return {
    title: guide.title,
    description: guide.description,
    content: (guideContent as Record<string, string>)[slug] ?? "",
  };
}
