import type { createClient } from "@supabase/supabase-js";
import { escapeHtml } from "@/lib/utils/escape-html";
import { Resend } from "resend";
import { EMAIL_FROM } from "@/lib/email/send";
import { getOrgTimeZone } from "@/lib/time/org-timezone";
import { shiftYmd, todayInZone } from "@/lib/time/zone";

/**
 * The CMMS automation executor (automations table: meter/part/PM/WO/request/
 * PO triggers → create WO/MR/requisition, notify, email). Shared by
 * /api/automations/run (cron poll + in-app event mode) and by server code
 * that causes an event itself (submitWorkRequest), so "what happens" is the
 * same no matter which path fired the rule. Server-only: every caller passes
 * a service-role client and has already resolved the org.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AdminClient = ReturnType<typeof createClient<any>>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AutomationRow = Record<string, any>;

// Trigger types that correspond to a discrete event (something was created,
// something's status changed) rather than a standing condition — these are
// fired directly by the code path that causes the event, not by polling.
export const EVENT_TRIGGER_TYPES = ["request_submitted", "wo_status_change", "po_status_change"] as const;
export type EventTriggerType = typeof EVENT_TRIGGER_TYPES[number];

export const SUPPORTED_ACTION_TYPES = [
  "create_work_order",
  "create_wo_request",
  "create_requisition",
  "send_notification",
  "send_email",
];

export interface ActionContext {
  orgId: string;
  assetId?: string | null;
  assetName?: string | null;
  /** The user whose action fired this rule (event mode). Never notified of
   *  their own action — see send_notification. Null for cron / anonymous. */
  actorUserId?: string | null;
}

/**
 * Executes one automation's configured action. Shared by every trigger type
 * (polled or event-fired) so "what happens" is identical regardless of
 * "when it fires" — this was extracted from the old meter-only inline logic
 * so part_low_stock/pm_due/wo_overdue/request_submitted/wo_status_change/
 * po_status_change could reuse it instead of duplicating five branches.
 */
export async function executeAction(
  adminClient: AdminClient,
  auto: AutomationRow,
  ctx: ActionContext
): Promise<{ result: string } | { skipReason: string }> {
  const ac = (auto.action_config ?? {}) as Record<string, unknown>;
  const acTitle = (ac.title as string) ?? "Automated Work Order";
  const acPriority = (ac.priority as string) ?? "medium";
  const orgId = ctx.orgId;

  if (auto.action_type === "create_work_order") {
    // Atomic per-org/year counter, not Date.now() — see next_work_order_number().
    const { data: workOrderNumber, error: woNumErr } = await adminClient.rpc("next_work_order_number", {
      p_org_id_override: orgId,
    });
    if (woNumErr || !workOrderNumber) return { skipReason: `failed to generate WO number: ${woNumErr?.message ?? "unknown"}` };
    // A meter rule is preventive maintenance by definition (an oil change at
    // N hours), and counts toward PM compliance as due 7 days after the meter
    // trips — see v_pm_outcomes.
    const isMeterPM = auto.trigger_type === "meter_threshold";
    const meterDueDate = isMeterPM
      ? shiftYmd(todayInZone(await getOrgTimeZone(adminClient, orgId)), 7)
      : null;
    const { data: wo, error: woErr } = await adminClient
      .from("work_orders")
      .insert({
        org_id: orgId,
        title: acTitle,
        priority: acPriority,
        assigned_to_name: (ac.assigned_to as string) || null,
        status: "open",
        asset_id: ctx.assetId ?? null,
        asset_name: ctx.assetName ?? null,
        work_order_number: workOrderNumber,
        automation_id: auto.id,
        is_recurring: false,
        ...(isMeterPM && { wo_type: "preventive", due_date: meterDueDate }),
      })
      .select("id, work_order_number")
      .single();
    if (woErr || !wo) return { skipReason: `failed to create WO: ${woErr?.message ?? "unknown"}` };
    return { result: wo.work_order_number };
  }

  if (auto.action_type === "create_wo_request") {
    const requestNumber = `MR-${new Date().getFullYear()}-${Date.now()}`;
    const { data: mr, error: mrErr } = await adminClient
      .from("maintenance_requests")
      .insert({
        org_id: orgId,
        request_number: requestNumber,
        title: acTitle,
        priority: acPriority,
        status: "open",
        asset_id: ctx.assetId ?? null,
        asset_name: ctx.assetName ?? null,
        requested_by_name: "Automation",
        description: `Auto-generated by automation: ${auto.name}`,
        automation_id: auto.id,
      })
      .select("id, request_number")
      .single();
    if (mrErr || !mr) return { skipReason: `failed to create MR: ${mrErr?.message ?? "unknown"}` };

    try {
      const resendKey = process.env.RESEND_API_KEY;
      if (resendKey) {
        const { data: recipients } = await adminClient
          .from("profiles")
          .select("email, name, notification_prefs")
          .eq("org_id", orgId)
          .in("role", ["admin", "manager"]);

        const eligible = (recipients ?? []).filter((p: { email: string | null; notification_prefs: Record<string, unknown> | null }) => {
          if (!p.email) return false;
          const prefs = (p.notification_prefs ?? {}) as Record<string, unknown>;
          return prefs["emailNewMaintenanceRequest"] !== false;
        });

        if (eligible.length > 0) {
          const resend = new Resend(resendKey);
          const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://landscapt.com";
          const subject = `New maintenance request: ${acTitle}`;
          const link = `${siteUrl}/cmms/requests?id=${mr.id}`;
          await Promise.allSettled(
            eligible.map((p: { email: string | null; name: string | null }) =>
              resend.emails.send({
                from: EMAIL_FROM,
                to: p.email as string,
                subject,
                html: `<div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px 24px">
                  <h2 style="margin:0 0 8px;font-size:20px;color:#0f172a">New Maintenance Request</h2>
                  <p style="margin:0 0 4px;color:#475569">Hi ${escapeHtml(p.name ?? "there")},</p>
                  <p style="margin:0 0 24px;color:#475569">Automation <strong>${escapeHtml(auto.name)}</strong> created: <strong>${escapeHtml(`${mr.request_number} — ${acTitle}`)}</strong>.</p>
                  <a href="${link}" style="display:inline-block;padding:12px 24px;background:#60ab45;color:#fff;text-decoration:none;border-radius:6px;font-weight:600">Review Request</a>
                </div>`,
              })
            )
          );
        }
      }
    } catch {
      // best-effort — don't fail the automation run
    }
    return { result: mr.request_number };
  }

  if (auto.action_type === "create_requisition") {
    // Atomic per-org/year counter, not Date.now() — see next_requisition_number().
    const { data: requisitionNumber, error: reqNumErr } = await adminClient.rpc("next_requisition_number", {
      p_org_id_override: orgId,
    });
    if (reqNumErr || !requisitionNumber) return { skipReason: `failed to generate requisition number: ${reqNumErr?.message ?? "unknown"}` };
    const { data: req, error: reqErr } = await adminClient
      .from("requisitions")
      .insert({
        org_id: orgId,
        requisition_number: requisitionNumber,
        title: auto.name,
        status: "draft",
        requested_by_name: "Automation",
        notes: (ac.notes as string) || `Auto-generated by automation: ${auto.name}`,
      })
      .select("id, requisition_number")
      .single();
    if (reqErr || !req) return { skipReason: `failed to create requisition: ${reqErr?.message ?? "unknown"}` };
    return { result: req.requisition_number };
  }

  if (auto.action_type === "send_notification") {
    const recipientRole = (ac.recipient_role as string) ?? "all";
    const message = (ac.message as string) ?? `Automation "${auto.name}" triggered.`;

    let profileQuery = adminClient.from("profiles").select("id").eq("org_id", orgId);
    if (recipientRole !== "all") profileQuery = profileQuery.eq("role", recipientRole);
    // Never notify the actor about their own action.
    if (ctx.actorUserId) profileQuery = profileQuery.neq("id", ctx.actorUserId);

    const { data: profiles, error: profileErr } = await profileQuery;
    if (profileErr || !profiles?.length) {
      return { skipReason: `no profiles found for role "${recipientRole}"` };
    }

    const rows = profiles.map((p: { id: string }) => ({
      org_id: orgId,
      user_id: p.id,
      type: "automation_alert",
      title: "Automation Alert",
      message,
      entity_id: null,
      entity_type: null,
    }));
    const { error: notifErr } = await adminClient.from("notifications").insert(rows);
    if (notifErr) return { skipReason: `failed to insert notifications: ${notifErr.message}` };
    return { result: `notified ${profiles.length} user${profiles.length === 1 ? "" : "s"}` };
  }

  if (auto.action_type === "send_email") {
    const recipient = (ac.recipient as string) ?? "";
    if (!recipient) return { skipReason: "no recipient in action_config" };

    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) return { skipReason: "RESEND_API_KEY not configured" };

    const fromEmail = process.env.FROM_EMAIL ?? "noreply@landscapt.com";
    const subject = `Automation triggered: ${auto.name}`;
    const body = (ac.message as string)
      ? `${ac.message as string}\n\nTriggered by automation: ${auto.name}`
      : `Automation "${auto.name}" was triggered.`;

    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Authorization": `Bearer ${resendKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: fromEmail, to: [recipient], subject, text: body }),
    });
    if (!emailRes.ok) {
      const errText = await emailRes.text();
      return { skipReason: `email send failed: ${errText}` };
    }
    return { result: `email sent to ${recipient}` };
  }

  return { skipReason: `unsupported action_type: ${auto.action_type}` };
}

export interface EventFireResult {
  fired: { automationId: string; name: string; result: string }[];
  skipped: { automationId: string; reason: string }[];
}

/**
 * Fires every enabled automation of one event trigger type in one org.
 * `assetId` must already be verified as belonging to `orgId` by the caller.
 */
export async function fireEventAutomations(
  adminClient: AdminClient,
  params: {
    orgId: string;
    eventTrigger: EventTriggerType;
    toStatus?: string | null;
    assetId?: string | null;
    assetName?: string | null;
    actorUserId?: string | null;
  }
): Promise<EventFireResult> {
  const { orgId, eventTrigger, toStatus } = params;
  const { data: candidates } = await adminClient
    .from("automations")
    .select("*")
    .eq("trigger_type", eventTrigger)
    .eq("org_id", orgId)
    .eq("enabled", true)
    .in("action_type", SUPPORTED_ACTION_TYPES)
    .is("deleted_at", null);

  const fired: EventFireResult["fired"] = [];
  const skipped: EventFireResult["skipped"] = [];
  const now = new Date().toISOString();

  for (const auto of (candidates ?? []) as AutomationRow[]) {
    if (eventTrigger === "wo_status_change" || eventTrigger === "po_status_change") {
      const tc = (auto.trigger_config ?? {}) as Record<string, unknown>;
      if (tc.to_status !== toStatus) {
        skipped.push({ automationId: auto.id, reason: `toStatus "${toStatus}" doesn't match configured "${tc.to_status}"` });
        continue;
      }
    }

    const outcome = await executeAction(adminClient, auto, {
      orgId,
      assetId: params.assetId ?? null,
      assetName: params.assetId ? (params.assetName ?? null) : null,
      actorUserId: params.actorUserId ?? null,
    });
    if ("skipReason" in outcome) {
      skipped.push({ automationId: auto.id, reason: outcome.skipReason });
      continue;
    }

    await adminClient
      .from("automations")
      .update({ last_fired_at: now, updated_at: now })
      .eq("id", auto.id);
    fired.push({ automationId: auto.id, name: auto.name, result: outcome.result });
  }
  return { fired, skipped };
}
