import { NextResponse } from "next/server";

/** Apple Pay requires each domain that renders a Payment Element offering it to serve
 * this exact file, unmodified, at this exact path. The content is generated by Stripe
 * per Stripe account + domain (Dashboard > Settings > Payment methods > Apple Pay) —
 * it is not something we can compute here. Set STRIPE_APPLE_PAY_DOMAIN_ASSOCIATION to
 * that file's raw contents so it can be updated without a code change, since it must be
 * regenerated for every new domain (e.g. moving off a *.vercel.app domain) and, for a
 * Stripe Connect direct-charge setup like ours, potentially per connected account too. */
export async function GET() {
  const contents = process.env.STRIPE_APPLE_PAY_DOMAIN_ASSOCIATION;
  if (!contents) {
    return new NextResponse("Apple Pay domain association file is not configured", { status: 404 });
  }
  return new NextResponse(contents, {
    headers: { "Content-Type": "text/plain" },
  });
}
