export const CLIENT_SELECT =
  "id, display_name, first_name, last_name, account_number, account_type, status, primary_phone, primary_email, billing_address, billing_city, billing_state, billing_zip, billing_email, billing_same_as_service, service_address, service_city, service_state, service_zip, source, parent_client_id, sales_rep_id, referred_by, referred_by_client_id, ok_to_email, do_not_market, sms_opt_in, sms_opt_in_at, sms_opt_in_source, payment_method, billing_terms, invoice_frequency, invoice_delivery, default_tax_rate_bps, default_terms, default_payment_method, is_taxable, gate_lock_code, notes_to_crew, map_code, office_notes, priority, turf_sqft, mulch_bed_sqft, gross_sqft, linear_ft_perimeter, linear_ft_edging, yards_of_mulch, client_since, created_at, updated_at";

export function shapeClient(row: Record<string, unknown>) {
  return {
    id: row.id,
    displayName: row.display_name,
    firstName: row.first_name,
    lastName: row.last_name,
    accountNumber: row.account_number,
    accountType: row.account_type,
    status: row.status,
    primaryPhone: row.primary_phone,
    primaryEmail: row.primary_email,
    billingAddress: row.billing_address,
    billingCity: row.billing_city,
    billingState: row.billing_state,
    billingZip: row.billing_zip,
    billingEmail: row.billing_email,
    billingSameAsService: row.billing_same_as_service,
    serviceAddress: row.service_address,
    serviceCity: row.service_city,
    serviceState: row.service_state,
    serviceZip: row.service_zip,
    source: row.source,
    parentClientId: row.parent_client_id,
    salesRepId: row.sales_rep_id,
    referredBy: row.referred_by,
    referredByClientId: row.referred_by_client_id,
    okToEmail: row.ok_to_email,
    doNotMarket: row.do_not_market,
    smsOptIn: row.sms_opt_in,
    // Read back alongside the flag: an A2P 10DLC audit needs the consent
    // record, not just the boolean.
    smsOptInAt: row.sms_opt_in_at,
    smsOptInSource: row.sms_opt_in_source,
    paymentMethod: row.payment_method,
    billingTerms: row.billing_terms,
    invoiceFrequency: row.invoice_frequency,
    invoiceDelivery: row.invoice_delivery,
    defaultTaxRateBps: row.default_tax_rate_bps,
    defaultTerms: row.default_terms,
    defaultPaymentMethod: row.default_payment_method,
    isTaxable: row.is_taxable,
    gateCode: row.gate_lock_code,
    notesToCrew: row.notes_to_crew,
    mapCode: row.map_code,
    officeNotes: row.office_notes,
    priority: row.priority,
    turfSqft: row.turf_sqft,
    mulchBedSqft: row.mulch_bed_sqft,
    grossSqft: row.gross_sqft,
    linearFtPerimeter: row.linear_ft_perimeter,
    linearFtEdging: row.linear_ft_edging,
    yardsOfMulch: row.yards_of_mulch,
    clientSince: row.client_since,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}
