import { BaseRecord } from "./common";
import type { CostLayer } from "@/lib/cost-methods";

export type WorkOrderStatus = "open" | "on_hold" | "in_progress" | "done" | "skipped";
export type WorkOrderPriority = "low" | "medium" | "high" | "critical";

export interface WorkOrder extends BaseRecord {
  title: string;
  description: string | null;
  status: WorkOrderStatus;
  priority: WorkOrderPriority;
  /** Reactive = unplanned/breakdown; Preventive = scheduled maintenance */
  woType: "reactive" | "preventive" | null;
  assetId: string | null;
  assetName: string | null;
  /** Disambiguates whether assetId points to an asset or vehicle record */
  linkedEntityType: "asset" | "vehicle" | null;
  assignedToId: string | null;
  assignedToName: string | null;
  /** All assigned user IDs (multi-assignee). First entry matches assignedToId. */
  assignedToIds: string[];
  /** All assigned user display names (multi-assignee). First entry matches assignedToName. */
  assignedToNames: string[];
  startDate: string | null;
  dueDate: string | null;
  category: string | null;
  /** All assigned category IDs (multi-category). First entry matches category. */
  categories: string[];
  workOrderNumber: string;
  /**
   * When set, this WO is a sub-work-order of the referenced parent WO.
   * Parent WOs have parentWorkOrderId = null and have 2+ children.
   */
  parentWorkOrderId: string | null;
  /**
   * When set, this WO was generated by a PM schedule and recurs on that schedule.
   * Null for one-off work orders.
   */
  pmScheduleId: string | null;
  /**
   * When true, this WO auto-generates a copy on the given recurrenceFrequency
   * after it is marked done.
   */
  isRecurring: boolean;
  recurrenceFrequency: "daily" | "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly" | null;
  /** Set when this WO was created by an automation rule. Used to advance the threshold on completion. */
  automationId: string | null;
  /** When the WO last moved to done (DB trigger); null while not done. */
  completedAt: string | null;
}

export type PaymentMethod = "outright" | "loan" | "lease" | "rental";

export type AssetStatus = "active" | "inactive" | "in_shop" | "out_of_service" | "disposed";

export interface Asset extends BaseRecord {
  name: string;
  assetTag: string;
  equipmentNumber: string | null;
  assetType: string;
  status: AssetStatus;
  make: string | null;
  model: string | null;
  year: number | null;
  serialNumber: string | null;
  engineSerialNumber: string | null;
  airFilterPartNumber: string | null;
  oilFilterPartNumber: string | null;
  sparkPlugPartNumber: string | null;
  division: string | null;
  engineModel: string | null;
  manufacturer: string | null;
  assignedCrew: string | null;
  barcode: string | null;
  parentAssetId: string | null;
  purchaseVendorId: string | null;
  purchaseVendorName: string | null;
  purchaseDate: string | null;
  purchasePrice: number | null; // cents
  paymentMethod: PaymentMethod | null;
  financeInstitution: string | null;
  location: string | null;
  photoUrl: string | null;
  notes: string | null;
  /** Optional license plate for assets that are registered vehicles or tagged equipment. */
  licensePlate: string | null;
  /** YYYY-MM-DD — when warranty coverage began (defaults to the purchase date in the form). */
  warrantyStartDate: string | null;
  /** Set when the warranty was entered as a period; the end date is derived from start + term. */
  warrantyTermMonths: number | null;
  /** YYYY-MM-DD — the date coverage ends. Source of truth for every warranty report. */
  warrantyEndDate: string | null;
  warrantyNotes: string | null;
}

export interface AssetPart extends BaseRecord {
  assetId: string;
  partId: string;
  partName: string;
  partNumber: string;
}

export interface Vehicle extends Asset {
  licensePlate: string | null;
  vin: string | null;
  samsaraVehicleId: string | null; // for Samsara API
  fuelType: string | null;
  /** YYYY-MM-DD — next oil change due date; null if not tracked */
  nextOilChangeDue: string | null;
  /** Odometer reading (miles) at which the next oil change is due; null if not tracked */
  nextOilChangeMileage: number | null;
  /** YYYY-MM-DD — next inspection sticker expiration date; null if not tracked */
  nextInspectionStickerDue: string | null;
}

export interface PartVendor {
  vendorId: string;
  vendorName: string;
}

export interface Part extends BaseRecord {
  name: string;
  partNumber: string;
  description: string;
  /** Primary category (first element of categories, kept for compat). Use `categories` for display. */
  category: string;
  /** All selected categories — the source of truth for multi-category parts. */
  categories: string[];
  quantityOnHand: number;
  minimumStock: number;
  unitCost: number; // cents — cost we pay from vendor
  vendorId: string | null;
  vendorName: string | null;
  alternateVendors: PartVendor[];
  parentPartId: string | null; // for interchangeable/generic sub-parts
  isInventory: boolean;
  pictureUrl: string | null;
  /** Storage location for this part (shared list with assets/vehicles) */
  location: string | null;
  /**
   * FK to ProductItem (category: maintenance_part).
   * When set, this Part is the CMMS inventory record for that purchasing catalog entry.
   * GoodsReceipt is the only mechanism that increments quantityOnHand for linked parts.
   */
  productItemId: string | null;
  /** Receipt history used for WAC and FIFO cost calculations. */
  costLayers: CostLayer[];
}

/** A single asset/vehicle entry within a PM schedule. */
export interface PMScheduleAsset extends BaseRecord {
  pmScheduleId: string;
  assetId: string;
  assetName: string;
}

/** A parts template entry scoped to one asset within a PM schedule. */
export interface PMScheduleAssetPart extends BaseRecord {
  pmScheduleAssetId: string;
  partId: string | null;
  partName: string;
  partNumber: string;
  quantity: number;
  unitCost: number; // cents
}

export interface PMSchedule extends BaseRecord {
  title: string;
  /** Nullable — multi-asset schedules use the pm_schedule_assets join table. */
  assetId: string | null;
  assetName: string;
  frequency: "daily" | "weekly" | "monthly" | "quarterly" | "annual";
  nextDueDate: string;
  lastCompletedDate: string | null;
  isActive: boolean;
  description: string | null;
  /** Default assignee pre-populated onto generated work orders. */
  assignedToId: string | null;
  assignedToName: string | null;
}

export interface Meter extends BaseRecord {
  name: string;
  assetId: string;
  assetName: string;
  unit: string; // "miles", "hours", "gallons", etc.
  currentValue: number;
  lastReadingAt: string;
  source: "manual" | "samsara";
}

export interface MeterReading extends BaseRecord {
  meterId: string;
  value: number;
  readingAt: string; // ISO datetime
  source: "manual" | "samsara";
  recordedByName: string | null;
  notes: string | null;
}

export interface WOPart extends BaseRecord {
  workOrderId: string;
  partId: string;
  partName: string;
  partNumber: string;
  quantity: number;
  unitCost: number; // cents
}

export interface PMPart extends BaseRecord {
  pmScheduleId: string;
  partId: string;
  partName: string;
  partNumber: string;
  quantity: number;
  unitCost: number; // cents
}

export interface WOLaborEntry extends BaseRecord {
  workOrderId: string;
  technicianName: string;
  description: string;
  hours: number;
  hourlyRate: number; // cents
}

export interface WOVendorCharge extends BaseRecord {
  workOrderId: string;
  vendorId: string | null;
  vendorName: string;
  description: string;
  cost: number; // cents
}

export type MaintenanceRequestStatus = "open" | "in_review" | "approved" | "converted" | "rejected";

export interface MaintenanceRequest extends BaseRecord {
  requestNumber: string;
  title: string;
  description: string | null;
  status: MaintenanceRequestStatus;
  priority: WorkOrderPriority;
  assetId: string | null;
  assetName: string | null;
  requestedById: string;
  requestedByName: string;
  linkedWorkOrderId: string | null;
  linkedWorkOrderNumber: string | null;
  /** Set when this request was created by an automation rule. Passed to the converted WO to enable threshold advancement on completion. */
  automationId: string | null;
  /** Type of equipment (e.g. "Vehicle", "Mower", "Trailer") */
  equipmentType: string | null;
  /** General repair/maintenance category (e.g. "Engine", "Hydraulics") */
  repairCategory: string | null;
  /** Whether the submitter placed a repair tag on the item */
  hasRepairTag: boolean | null;
}

/** One row of cmms_asset_metrics(): reliability + cost figures for an asset or vehicle. */
export interface AssetMetrics {
  entityType: "asset" | "vehicle";
  assetId: string;
  name: string;
  assetTag: string;
  assetType: string;
  status: AssetStatus;
  location: string | null;
  purchasePrice: number | null; // cents
  warrantyEndDate: string | null;
  windowDays: number;
  /** Active time ÷ (active + in-shop + out-of-service time); null with no in-service time in the window. */
  uptimePct: number | null;
  inServiceHours: number;
  downtimeHours: number;
  downtimeEvents: number;
  /** Mean time to repair: average length of down periods that started and ended in the window. */
  mttrHours: number | null;
  /** Set while the asset is currently in the shop / out of service. */
  downSince: string | null;
  woCount: number;
  openWoCount: number;
  cost12moCents: number;
  pmCost12moCents: number;
  costLifetimeCents: number;
  pmCostLifetimeCents: number;
  pmDue: number;
  pmCompleted: number;
  pmOnTime: number;
  pmLate: number;
  pmSkipped: number;
  pmOverdue: number;
  /** Cycles whose due date passed without a work order being generated. */
  pmNotGenerated: number;
}

export type PMOutcome = "on_time" | "late" | "completed" | "skipped" | "overdue" | "not_generated" | "pending";

/**
 * One row of v_pm_outcomes: a scheduled or meter-triggered PM on one asset and
 * how it counts toward compliance. A cycle that was never generated has no
 * work order (outcome "not_generated").
 */
export interface PMOutcomeRow {
  source: "schedule" | "meter";
  /** The PM schedule, or the meter automation, this PM belongs to. */
  programId: string;
  programName: string | null;
  workOrderId: string | null;
  workOrderNumber: string | null;
  assetId: string | null;
  assetName: string | null;
  dueDate: string | null;
  /** The due date, or the day it was generated when it has none. */
  dueOn: string;
  completedOn: string | null;
  outcome: PMOutcome;
}

/** A window when a PM schedule doesn't run (winter for mowers). Cycles due inside it aren't generated or scored. */
export interface PMSchedulePause {
  id: string;
  pmScheduleId: string;
  startsOn: string;
  /** First day the schedule runs again; null = paused until someone resumes it. */
  resumesOn: string | null;
  /** Repeat the same month/day window every year (needs resumesOn). */
  recursYearly: boolean;
  reason: string | null;
  createdAt: string;
}

export interface PMSchedulePauseState {
  pmScheduleId: string;
  currentPauseId: string | null;
  recursYearly: boolean | null;
  /** When the current pause ends; null while paused with no end date. */
  pausedUntil: string | null;
}
