import { BaseRecord } from "./common";
import type { CostLayer } from "@/lib/cost-methods";

export type WorkOrderStatus = "open" | "on_hold" | "in_progress" | "done";
export type WorkOrderPriority = "low" | "medium" | "high" | "critical";

export interface WorkOrder extends BaseRecord {
  title: string;
  description: string | null;
  status: WorkOrderStatus;
  priority: WorkOrderPriority;
  /** Reactive = unplanned/breakdown; Preventive = scheduled maintenance */
  woType: "reactive" | "preventive" | null;
  assetId: string | null;
  assetName: string | null;
  /** Disambiguates whether assetId points to an asset or vehicle record */
  linkedEntityType: "asset" | "vehicle" | null;
  assignedToId: string | null;
  assignedToName: string | null;
  /** All assigned user IDs (multi-assignee). First entry matches assignedToId. */
  assignedToIds: string[];
  /** All assigned user display names (multi-assignee). First entry matches assignedToName. */
  assignedToNames: string[];
  dueDate: string | null;
  category: string | null;
  /** All assigned category IDs (multi-category). First entry matches category. */
  categories: string[];
  workOrderNumber: string;
  /**
   * When set, this WO is a sub-work-order of the referenced parent WO.
   * Parent WOs have parentWorkOrderId = null and have 2+ children.
   */
  parentWorkOrderId: string | null;
  /**
   * When set, this WO was generated by a PM schedule and recurs on that schedule.
   * Null for one-off work orders.
   */
  pmScheduleId: string | null;
  /**
   * When true, this WO auto-generates a copy on the given recurrenceFrequency
   * after it is marked done.
   */
  isRecurring: boolean;
  recurrenceFrequency: "daily" | "weekly" | "biweekly" | "monthly" | "quarterly" | "yearly" | null;
}

export type PaymentMethod = "outright" | "loan" | "lease" | "rental";

export type AssetStatus = "active" | "inactive" | "in_shop" | "out_of_service" | "disposed";

export interface Asset extends BaseRecord {
  name: string;
  assetTag: string;
  equipmentNumber: string | null;
  assetType: string;
  status: AssetStatus;
  make: string | null;
  model: string | null;
  year: number | null;
  serialNumber: string | null;
  engineSerialNumber: string | null;
  airFilterPartNumber: string | null;
  oilFilterPartNumber: string | null;
  sparkPlugPartNumber: string | null;
  division: string | null;
  engineModel: string | null;
  manufacturer: string | null;
  assignedCrew: string | null;
  barcode: string | null;
  parentAssetId: string | null;
  purchaseVendorId: string | null;
  purchaseVendorName: string | null;
  purchaseDate: string | null;
  purchasePrice: number | null; // cents
  paymentMethod: PaymentMethod | null;
  financeInstitution: string | null;
  location: string | null;
  photoUrl: string | null;
  notes: string | null;
}

export interface AssetPart extends BaseRecord {
  assetId: string;
  partId: string;
  partName: string;
  partNumber: string;
}

export interface Vehicle extends Asset {
  licensePlate: string | null;
  vin: string | null;
  samsaraVehicleId: string | null; // for Samsara API
  fuelType: string | null;
  /** YYYY-MM-DD — next oil change due date; null if not tracked */
  nextOilChangeDue: string | null;
  /** Odometer reading (miles) at which the next oil change is due; null if not tracked */
  nextOilChangeMileage: number | null;
  /** YYYY-MM-DD — next inspection sticker expiration date; null if not tracked */
  nextInspectionStickerDue: string | null;
}

export interface PartVendor {
  vendorId: string;
  vendorName: string;
}

export interface Part extends BaseRecord {
  name: string;
  partNumber: string;
  description: string;
  category: string;
  quantityOnHand: number;
  minimumStock: number;
  unitCost: number; // cents — cost we pay from vendor
  vendorId: string | null;
  vendorName: string | null;
  alternateVendors: PartVendor[];
  parentPartId: string | null; // for interchangeable/generic sub-parts
  isInventory: boolean;
  pictureUrl: string | null;
  /** Storage location for this part (shared list with assets/vehicles) */
  location: string | null;
  /**
   * FK to ProductItem (category: maintenance_part).
   * When set, this Part is the CMMS inventory record for that purchasing catalog entry.
   * GoodsReceipt is the only mechanism that increments quantityOnHand for linked parts.
   */
  productItemId: string | null;
  /** Receipt history used for WAC and FIFO cost calculations. */
  costLayers: CostLayer[];
}

export interface PMSchedule extends BaseRecord {
  title: string;
  assetId: string;
  assetName: string;
  frequency: "daily" | "weekly" | "monthly" | "quarterly" | "annual";
  nextDueDate: string;
  lastCompletedDate: string | null;
  isActive: boolean;
  description: string | null;
}

export interface Meter extends BaseRecord {
  name: string;
  assetId: string;
  assetName: string;
  unit: string; // "miles", "hours", "gallons", etc.
  currentValue: number;
  lastReadingAt: string;
  source: "manual" | "samsara";
}

export interface MeterReading extends BaseRecord {
  meterId: string;
  value: number;
  readingAt: string; // ISO datetime
  source: "manual" | "samsara";
  recordedByName: string | null;
}

export interface WOPart extends BaseRecord {
  workOrderId: string;
  partId: string;
  partName: string;
  partNumber: string;
  quantity: number;
  unitCost: number; // cents
}

export interface WOLaborEntry extends BaseRecord {
  workOrderId: string;
  technicianName: string;
  description: string;
  hours: number;
  hourlyRate: number; // cents
}

export interface WOVendorCharge extends BaseRecord {
  workOrderId: string;
  vendorId: string | null;
  vendorName: string;
  description: string;
  cost: number; // cents
}

export type MaintenanceRequestStatus = "open" | "in_review" | "approved" | "converted" | "rejected";

export interface MaintenanceRequest extends BaseRecord {
  requestNumber: string;
  title: string;
  description: string | null;
  status: MaintenanceRequestStatus;
  priority: WorkOrderPriority;
  assetId: string | null;
  assetName: string | null;
  requestedById: string;
  requestedByName: string;
  linkedWorkOrderId: string | null;
  linkedWorkOrderNumber: string | null;
}
