import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createClient as createServerClient } from "@/lib/supabase/server";
import { Resend } from "resend";
import type { Database } from "@/types/supabase";
import { processDueEnrollment } from "@/lib/automations/sequence-processor";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AdminClient = ReturnType<typeof createClient<any>>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AutomationRow = Record<string, any>;

const SUPPORTED_ACTION_TYPES = [
  "create_work_order",
  "create_wo_request",
  "create_requisition",
  "send_notification",
  "send_email",
];

// Trigger types evaluated by polling current state on every run (meter
// value, stock level, due dates) — each needs the fire-once/reset-on-clear
// gating below since the underlying condition can stay true for days.
const POLL_TRIGGER_TYPES = ["meter_threshold", "part_low_stock", "pm_due", "wo_overdue"] as const;
// Trigger types that correspond to a discrete event (something was created,
// something's status changed) rather than a standing condition — these are
// fired directly by the code path that causes the event, via the eventTrigger
// body param below, not by polling.
const EVENT_TRIGGER_TYPES = ["request_submitted", "wo_status_change", "po_status_change"] as const;

interface ActionContext {
  orgId: string;
  assetId?: string | null;
  assetName?: string | null;
}

/**
 * Executes one automation's configured action. Shared by every trigger type
 * (polled or event-fired) so "what happens" is identical regardless of
 * "when it fires" — this was extracted from the old meter-only inline logic
 * so part_low_stock/pm_due/wo_overdue/request_submitted/wo_status_change/
 * po_status_change could reuse it instead of duplicating five branches.
 */
async function executeAction(
  adminClient: AdminClient,
  auto: AutomationRow,
  ctx: ActionContext
): Promise<{ result: string } | { skipReason: string }> {
  const ac = (auto.action_config ?? {}) as Record<string, unknown>;
  const acTitle = (ac.title as string) ?? "Automated Work Order";
  const acPriority = (ac.priority as string) ?? "medium";
  const orgId = ctx.orgId;

  if (auto.action_type === "create_work_order") {
    const workOrderNumber = `WO-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
    const { data: wo, error: woErr } = await adminClient
      .from("work_orders")
      .insert({
        org_id: orgId,
        title: acTitle,
        priority: acPriority,
        assigned_to_name: (ac.assigned_to as string) || null,
        status: "open",
        asset_id: ctx.assetId ?? null,
        asset_name: ctx.assetName ?? null,
        work_order_number: workOrderNumber,
        automation_id: auto.id,
        is_recurring: false,
      })
      .select("id, work_order_number")
      .single();
    if (woErr || !wo) return { skipReason: `failed to create WO: ${woErr?.message ?? "unknown"}` };
    return { result: wo.work_order_number };
  }

  if (auto.action_type === "create_wo_request") {
    const requestNumber = `MR-${new Date().getFullYear()}-${Date.now()}`;
    const { data: mr, error: mrErr } = await adminClient
      .from("maintenance_requests")
      .insert({
        org_id: orgId,
        request_number: requestNumber,
        title: acTitle,
        priority: acPriority,
        status: "open",
        asset_id: ctx.assetId ?? null,
        asset_name: ctx.assetName ?? null,
        requested_by_name: "Automation",
        description: `Auto-generated by automation: ${auto.name}`,
        automation_id: auto.id,
      })
      .select("id, request_number")
      .single();
    if (mrErr || !mr) return { skipReason: `failed to create MR: ${mrErr?.message ?? "unknown"}` };

    try {
      const resendKey = process.env.RESEND_API_KEY;
      if (resendKey) {
        const { data: recipients } = await adminClient
          .from("profiles")
          .select("email, name, notification_prefs")
          .eq("org_id", orgId)
          .in("role", ["admin", "manager"]);

        const eligible = (recipients ?? []).filter((p: { email: string | null; notification_prefs: Record<string, unknown> | null }) => {
          if (!p.email) return false;
          const prefs = (p.notification_prefs ?? {}) as Record<string, unknown>;
          return prefs["emailNewMaintenanceRequest"] !== false;
        });

        if (eligible.length > 0) {
          const resend = new Resend(resendKey);
          const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://twins-os.vercel.app";
          const subject = `New maintenance request: ${acTitle}`;
          const link = `${siteUrl}/cmms/work-orders`;
          await Promise.allSettled(
            eligible.map((p: { email: string | null; name: string | null }) =>
              resend.emails.send({
                from: "Equipt <noreply@twinslawnservice.com>",
                to: p.email as string,
                subject,
                html: `<div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px 24px">
                  <h2 style="margin:0 0 8px;font-size:20px;color:#0f172a">New Maintenance Request</h2>
                  <p style="margin:0 0 4px;color:#475569">Hi ${p.name ?? "there"},</p>
                  <p style="margin:0 0 24px;color:#475569">Automation <strong>${auto.name}</strong> created: <strong>${mr.request_number} — ${acTitle}</strong>.</p>
                  <a href="${link}" style="display:inline-block;padding:12px 24px;background:#60ab45;color:#fff;text-decoration:none;border-radius:6px;font-weight:600">Review Request</a>
                </div>`,
              })
            )
          );
        }
      }
    } catch {
      // best-effort — don't fail the automation run
    }
    return { result: mr.request_number };
  }

  if (auto.action_type === "create_requisition") {
    const requisitionNumber = `REQ-${new Date().getFullYear()}-${Date.now()}`;
    const { data: req, error: reqErr } = await adminClient
      .from("requisitions")
      .insert({
        org_id: orgId,
        requisition_number: requisitionNumber,
        title: auto.name,
        status: "draft",
        requested_by_name: "Automation",
        notes: (ac.notes as string) || `Auto-generated by automation: ${auto.name}`,
      })
      .select("id, requisition_number")
      .single();
    if (reqErr || !req) return { skipReason: `failed to create requisition: ${reqErr?.message ?? "unknown"}` };
    return { result: req.requisition_number };
  }

  if (auto.action_type === "send_notification") {
    const recipientRole = (ac.recipient_role as string) ?? "all";
    const message = (ac.message as string) ?? `Automation "${auto.name}" triggered.`;

    let profileQuery = adminClient.from("profiles").select("id").eq("org_id", orgId);
    if (recipientRole !== "all") profileQuery = profileQuery.eq("role", recipientRole);

    const { data: profiles, error: profileErr } = await profileQuery;
    if (profileErr || !profiles?.length) {
      return { skipReason: `no profiles found for role "${recipientRole}"` };
    }

    const rows = profiles.map((p: { id: string }) => ({ org_id: orgId, user_id: p.id, message }));
    const { error: notifErr } = await adminClient.from("notifications").insert(rows);
    if (notifErr) return { skipReason: `failed to insert notifications: ${notifErr.message}` };
    return { result: `notified ${profiles.length} user${profiles.length === 1 ? "" : "s"}` };
  }

  if (auto.action_type === "send_email") {
    const recipient = (ac.recipient as string) ?? "";
    if (!recipient) return { skipReason: "no recipient in action_config" };

    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) return { skipReason: "RESEND_API_KEY not configured" };

    const fromEmail = process.env.FROM_EMAIL ?? "noreply@twinsOS.com";
    const subject = `Automation triggered: ${auto.name}`;
    const body = (ac.message as string)
      ? `${ac.message as string}\n\nTriggered by automation: ${auto.name}`
      : `Automation "${auto.name}" was triggered.`;

    const emailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Authorization": `Bearer ${resendKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ from: fromEmail, to: [recipient], subject, text: body }),
    });
    if (!emailRes.ok) {
      const errText = await emailRes.text();
      return { skipReason: `email send failed: ${errText}` };
    }
    return { result: `email sent to ${recipient}` };
  }

  return { skipReason: `unsupported action_type: ${auto.action_type}` };
}

/** True if ANY part matching the automation's configured name (or "any") is
 *  at or below its minimum stock. A single automation only tracks one
 *  pending_reset flag, so — same tradeoff as meter_threshold — "any" mode
 *  fires once when at least one part goes low and won't re-fire until EVERY
 *  part has recovered above its minimum, rather than tracking each part's
 *  state individually. */
async function evaluatePartLowStock(adminClient: AdminClient, orgId: string, partName: string): Promise<boolean> {
  let q = adminClient
    .from("parts")
    .select("id, quantity_on_hand, minimum_stock")
    .eq("org_id", orgId)
    .is("deleted_at", null)
    .gt("minimum_stock", 0);
  if (partName && partName !== "any") q = q.ilike("name", partName);
  const { data } = await q;
  return (data ?? []).some((p: { quantity_on_hand: number; minimum_stock: number }) => p.quantity_on_hand <= p.minimum_stock);
}

/** True if any active PM schedule is due within daysAhead days. */
async function evaluatePmDue(adminClient: AdminClient, orgId: string, daysAhead: number): Promise<boolean> {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() + daysAhead);
  const { data } = await adminClient
    .from("pm_schedules")
    .select("id")
    .eq("org_id", orgId)
    .eq("is_active", true)
    .is("deleted_at", null)
    .lte("next_due_date", cutoff.toISOString().slice(0, 10))
    .limit(1);
  return (data ?? []).length > 0;
}

/** True if any open work order's due date is more than daysOverdue days in the past. */
async function evaluateWoOverdue(adminClient: AdminClient, orgId: string, daysOverdue: number): Promise<boolean> {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysOverdue);
  const { data } = await adminClient
    .from("work_orders")
    .select("id")
    .eq("org_id", orgId)
    .is("deleted_at", null)
    .not("status", "in", '("done","skipped")')
    .not("due_date", "is", null)
    .lte("due_date", cutoff.toISOString().slice(0, 10))
    .limit(1);
  return (data ?? []).length > 0;
}

/**
 * GET  /api/automations/run — called by Vercel Cron (GET only), polls every
 *      standing-condition trigger type (meter/part-stock/PM-due/WO-overdue).
 * POST /api/automations/run — two modes:
 *   1. No body (or no eventTrigger key) — same poll sweep as GET, for an
 *      authenticated admin triggering manually.
 *   2. { eventTrigger, ... } — fires only automations of that ONE event
 *      trigger type, called by the app itself right after the event
 *      happens (a maintenance request created, a WO/PO status changed).
 */
export async function GET(request: Request) {
  return handleRun(request);
}

export async function POST(request: Request) {
  return handleRun(request);
}

async function handleRun(request: Request) {
  const adminClient = createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // ── Auth ──────────────────────────────────────────────────────────────────
  const authHeader = request.headers.get("Authorization") ?? "";
  const isCron =
    process.env.CRON_SECRET &&
    authHeader === `Bearer ${process.env.CRON_SECRET}`;

  let callerOrgId: string | null = null;

  if (!isCron) {
    const userClient = await createServerClient();
    const {
      data: { user },
      error: authErr,
    } = await userClient.auth.getUser();
    if (authErr || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const { data: profile } = await userClient
      .from("profiles")
      .select("org_id")
      .eq("id", user.id)
      .single();
    if (!profile) {
      return NextResponse.json({ error: "Profile not found" }, { status: 403 });
    }
    callerOrgId = profile.org_id;
  }

  // ── Event-fired mode ──────────────────────────────────────────────────────
  // Only reachable via POST from an authenticated (non-cron) caller — the app
  // calls this right after the triggering event, scoped to the caller's own org.
  if (request.method === "POST") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let body: any = {};
    try { body = await request.json(); } catch { /* no/invalid body — fall through to poll mode */ }

    if (body?.eventTrigger && (EVENT_TRIGGER_TYPES as readonly string[]).includes(body.eventTrigger)) {
      if (!callerOrgId) {
        return NextResponse.json({ error: "Event-fired automations require an authenticated caller" }, { status: 401 });
      }
      const { eventTrigger, toStatus, assetId, assetName } = body as {
        eventTrigger: typeof EVENT_TRIGGER_TYPES[number];
        toStatus?: string;
        assetId?: string | null;
        assetName?: string | null;
      };

      let autoQuery = (adminClient as AdminClient)
        .from("automations")
        .select("*")
        .eq("trigger_type", eventTrigger)
        .eq("org_id", callerOrgId)
        .eq("enabled", true)
        .in("action_type", SUPPORTED_ACTION_TYPES)
        .is("deleted_at", null);

      const { data: candidates } = await autoQuery;
      const fired: { automationId: string; name: string; result: string }[] = [];
      const skipped: { automationId: string; reason: string }[] = [];
      const now = new Date().toISOString();

      for (const auto of candidates ?? []) {
        if (eventTrigger === "wo_status_change" || eventTrigger === "po_status_change") {
          const tc = (auto.trigger_config ?? {}) as Record<string, unknown>;
          if (tc.toStatus !== toStatus) {
            skipped.push({ automationId: auto.id, reason: `toStatus "${toStatus}" doesn't match configured "${tc.toStatus}"` });
            continue;
          }
        }

        const outcome = await executeAction(adminClient as AdminClient, auto, {
          orgId: callerOrgId,
          assetId: assetId ?? null,
          assetName: assetName ?? null,
        });
        if ("skipReason" in outcome) {
          skipped.push({ automationId: auto.id, reason: outcome.skipReason });
          continue;
        }

        await (adminClient as AdminClient)
          .from("automations")
          .update({ last_fired_at: now, updated_at: now })
          .eq("id", auto.id);
        fired.push({ automationId: auto.id, name: auto.name, result: outcome.result });
      }

      return NextResponse.json({ fired: fired.length, skipped: skipped.length, details: { fired, skipped } });
    }
  }

  // ── Poll sweep (meter_threshold, part_low_stock, pm_due, wo_overdue) ───────
  let autoQuery = (adminClient as AdminClient)
    .from("automations")
    .select("*")
    .in("trigger_type", POLL_TRIGGER_TYPES)
    .in("action_type", SUPPORTED_ACTION_TYPES)
    .eq("enabled", true)
    .is("deleted_at", null);

  if (callerOrgId) {
    autoQuery = autoQuery.eq("org_id", callerOrgId);
  }

  const { data: automations, error: autoErr } = await autoQuery;
  if (autoErr) {
    return NextResponse.json({ error: autoErr.message }, { status: 500 });
  }

  const fired: { automationId: string; name: string; result: string }[] = [];
  const skipped: { automationId: string; reason: string }[] = [];
  const now = new Date().toISOString();

  for (const auto of automations ?? []) {
    const tc = (auto.trigger_config ?? {}) as Record<string, unknown>;
    const orgId = auto.org_id as string;

    if (auto.trigger_type === "meter_threshold") {
      const meterId = tc.meter_id as string | undefined;
      const threshold = Number(tc.threshold ?? 0);
      const operator = (tc.operator as string | undefined) ?? ">=";

      if (!meterId) {
        skipped.push({ automationId: auto.id, reason: "no meter_id in trigger_config" });
        continue;
      }

      const { data: meter, error: meterErr } = await (adminClient as AdminClient)
        .from("meters")
        .select("id, current_value, asset_id, asset_name, org_id")
        .eq("id", meterId)
        .is("deleted_at", null)
        .single();
      if (meterErr || !meter) {
        skipped.push({ automationId: auto.id, reason: "meter not found" });
        continue;
      }

      const currentValue = Number(meter.current_value ?? 0);
      const triggered = operator === ">=" ? currentValue >= threshold : currentValue <= threshold;

      if (!triggered) {
        if (auto.pending_reset) {
          await (adminClient as AdminClient).from("automations").update({ pending_reset: false, updated_at: now }).eq("id", auto.id);
        }
        skipped.push({ automationId: auto.id, reason: `meter value ${currentValue} does not satisfy ${operator} ${threshold}` });
        continue;
      }
      if (auto.pending_reset) {
        skipped.push({ automationId: auto.id, reason: "already fired, waiting for meter to reset" });
        continue;
      }

      const outcome = await executeAction(adminClient as AdminClient, auto, {
        orgId, assetId: meter.asset_id ?? null, assetName: meter.asset_name ?? null,
      });
      if ("skipReason" in outcome) { skipped.push({ automationId: auto.id, reason: outcome.skipReason }); continue; }

      await (adminClient as AdminClient)
        .from("automations")
        .update({ last_fired_at: now, last_fired_value: currentValue, pending_reset: true, updated_at: now })
        .eq("id", auto.id);
      fired.push({ automationId: auto.id, name: auto.name, result: outcome.result });
      continue;
    }

    // part_low_stock / pm_due / wo_overdue — all use the same fire-once /
    // clear-on-resolve gating as meter_threshold above, just with a
    // different condition check and no asset context.
    let triggered: boolean;
    let notMetReason: string;
    if (auto.trigger_type === "part_low_stock") {
      triggered = await evaluatePartLowStock(adminClient as AdminClient, orgId, (tc.partName as string) ?? "any");
      notMetReason = "no matching part is at or below its minimum stock";
    } else if (auto.trigger_type === "pm_due") {
      triggered = await evaluatePmDue(adminClient as AdminClient, orgId, Number(tc.daysAhead ?? 7));
      notMetReason = "no active PM schedule is due within the configured window";
    } else if (auto.trigger_type === "wo_overdue") {
      triggered = await evaluateWoOverdue(adminClient as AdminClient, orgId, Number(tc.daysOverdue ?? 1));
      notMetReason = "no open work order is overdue by the configured amount";
    } else {
      skipped.push({ automationId: auto.id, reason: `unsupported poll trigger_type: ${auto.trigger_type}` });
      continue;
    }

    if (!triggered) {
      if (auto.pending_reset) {
        await (adminClient as AdminClient).from("automations").update({ pending_reset: false, updated_at: now }).eq("id", auto.id);
      }
      skipped.push({ automationId: auto.id, reason: notMetReason });
      continue;
    }
    if (auto.pending_reset) {
      skipped.push({ automationId: auto.id, reason: "already fired, waiting for condition to clear" });
      continue;
    }

    const outcome = await executeAction(adminClient as AdminClient, auto, { orgId });
    if ("skipReason" in outcome) { skipped.push({ automationId: auto.id, reason: outcome.skipReason }); continue; }

    await (adminClient as AdminClient)
      .from("automations")
      .update({ last_fired_at: now, pending_reset: true, updated_at: now })
      .eq("id", auto.id);
    fired.push({ automationId: auto.id, name: auto.name, result: outcome.result });
  }

  // ── CRM sequence enrollment processor ────────────────────────────────────
  const crmFired: { enrollmentId: string; action: string }[] = [];
  const crmSkipped: { enrollmentId: string; reason: string }[] = [];

  try {
    const nowIso = new Date().toISOString();

    let enrollQuery = (adminClient as AdminClient)
      .from("crm_sequence_enrollments")
      .select("id, org_id, sequence_id, client_id, estimate_id, ticket_id, invoice_id, next_event_position")
      .lte("next_fire_at", nowIso)
      .is("completed_at", null)
      .is("stopped_at", null)
      .is("deleted_at", null)
      .eq("awaiting_approval", false)
      .limit(50);

    if (callerOrgId) {
      enrollQuery = enrollQuery.eq("org_id", callerOrgId);
    }

    const { data: enrollments, error: enrollErr } = await enrollQuery;
    if (enrollErr) {
      console.error("[crm-processor] enrollment query error:", enrollErr.message);
    }

    for (const enrollment of enrollments ?? []) {
      const outcome = await processDueEnrollment(adminClient, enrollment);
      if ("fired" in outcome) {
        crmFired.push(outcome.fired);
      } else {
        crmSkipped.push(outcome.skipped);
      }
    }
  } catch (crmErr) {
    console.error("[crm-processor] fatal error:", crmErr);
  }

  return NextResponse.json({
    fired: fired.length,
    skipped: skipped.length,
    details: { fired, skipped },
    crm: { fired: crmFired.length, skipped: crmSkipped.length, details: { fired: crmFired, skipped: crmSkipped } },
  });
}
