import type { DashboardConfig } from "@/types/crm-reports";

// ============================================================
// Starter dashboard templates offered from the "New Dashboard" flow.
// Selecting one pre-fills the builder (not saved until the user hits
// Save) so it's a starting point, not a fixed dashboard.
// ============================================================

export interface DashboardTemplate {
  key: string;
  name: string;
  description: string;
  /** Auto-cloned into every org as a real, editable dashboard on their first
   *  Report Center visit (see ensureSystemDashboardsSeeded). Templates without
   *  this flag stay picker-only starting points, same as before. */
  seedable?: boolean;
  config: DashboardConfig;
}

export const DASHBOARD_TEMPLATES: DashboardTemplate[] = [
  {
    key: "sales-overview",
    name: "Sales Overview",
    description: "Estimate pipeline, win rate, and recent activity.",
    seedable: true,
    config: {
      tabs: [
        {
          id: "overview",
          name: "Overview",
          useDateFilter: true,
          panels: [
            {
              id: "invoiced-revenue-ytd",
              title: "Invoiced Revenue (YTD)",
              size: "third",
              visual: {
                type: "gauge",
                useTabDateRange: true,
                kpiColumn: "sum_total_cents",
                valueColumns: [],
                gaugeMax: 400000000,
                config: {
                  dataset: "rpt_invoices",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "void" }],
                  groupBy: [],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "new-leads-ytd",
              title: "New Leads YTD",
              size: "third",
              visual: {
                type: "gauge",
                useTabDateRange: true,
                dateColumn: "created_at",
                kpiColumn: "count_all",
                valueColumns: [],
                gaugeMax: 600,
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "eq", value: "lead" }],
                  groupBy: [],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "new-clients-ytd",
              title: "New Clients / Converted Leads YTD",
              size: "third",
              visual: {
                type: "gauge",
                useTabDateRange: true,
                kpiColumn: "count_all",
                valueColumns: [],
                gaugeMax: 300,
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: [],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "clients-leads-monthly",
              title: "Clients/Leads",
              size: "full",
              reportKey: "clients-leads-monthly-matrix",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "close-ratios-by-sales-rep",
              title: "Close Ratios by Sales Rep",
              size: "half",
              reportKey: "close-ratios-by-sales-rep",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "clients-leads-stats",
              title: "Clients and Leads",
              size: "half",
              reportKey: "clients-leads-stats",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "open-estimates-leaderboard",
              title: "Open Estimates Leaderboard",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortColumn: "count_all",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "won-estimates-leaderboard",
              title: "Won Estimates Leaderboard",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["accepted", "invoiced"] }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "sales-activity-7-days",
              title: "Sales Activity (Last 7 Days)",
              size: "half",
              reportKey: "sales-activity-last-7-days",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "company-scorecard",
              title: "Company Scorecard",
              size: "full",
              reportKey: "company-scorecard",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "leads",
          name: "Leads",
          useDateFilter: true,
          panels: [
            {
              id: "leads-by-source-bar",
              title: "Leads by Source (count-YTD)",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                dateColumn: "created_at",
                labelColumn: "source",
                valueColumns: ["count_all"],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "eq", value: "lead" }],
                  groupBy: ["source"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortColumn: "count_all",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "leads-ytd-gauge",
              title: "Leads YTD",
              size: "half",
              visual: {
                type: "gauge",
                useTabDateRange: true,
                dateColumn: "created_at",
                kpiColumn: "count_all",
                valueColumns: [],
                gaugeMax: 600,
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "eq", value: "lead" }],
                  groupBy: [],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "leads-by-source-pie",
              title: "Leads by Source (%-YTD)",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: true,
                dateColumn: "created_at",
                labelColumn: "source",
                valueColumns: ["count_all"],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "eq", value: "lead" }],
                  groupBy: ["source"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortColumn: "count_all",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "new-leads-this-month",
              title: "New Leads This Month",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: true,
                dateColumn: "created_at",
                valueColumns: [],
                config: {
                  dataset: "rpt_clients",
                  columns: ["display_name", "source", "sales_rep", "created_at"],
                  filters: [{ column: "status", op: "eq", value: "lead" }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "created_at",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "lead-aging-summary",
              title: "Lead Aging Summary",
              size: "full",
              reportKey: "lead-aging-summary",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "new-leads-report",
              title: "New Leads Report",
              size: "full",
              reportKey: "new-leads",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "sales-summary-by-source",
              title: "Sales Summary by Source",
              size: "full",
              reportKey: "sales-summary-by-source",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "closed-leads-summary",
              title: "Closed Leads Summary",
              size: "full",
              reportKey: "closed-leads-summary",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "new-clients",
          name: "New Clients",
          useDateFilter: true,
          panels: [
            {
              id: "clients-by-source-bar",
              title: "Clients by Source (count-YTD)",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                labelColumn: "source",
                valueColumns: ["count_all"],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: ["source"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortColumn: "count_all",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "clients-by-source-pie",
              title: "Clients by Source (%-YTD)",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: true,
                labelColumn: "source",
                valueColumns: ["count_all"],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: ["source"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortColumn: "count_all",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "new-clients-this-month",
              title: "New Clients This Month",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_clients",
                  columns: ["display_name", "sales_rep", "primary_phone", "client_since"],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "client_since",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "new-clients-ytd-gauge",
              title: "New Clients YTD",
              size: "half",
              visual: {
                type: "gauge",
                useTabDateRange: true,
                kpiColumn: "count_all",
                valueColumns: [],
                gaugeMax: 300,
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: [],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "new-client-count-report",
              title: "New Client Count Report",
              size: "full",
              reportKey: "new-client-count",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "new-clients-report",
              title: "New Clients Report",
              size: "full",
              reportKey: "new-clients",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "estimates",
          name: "Estimates",
          useDateFilter: true,
          panels: [
            {
              id: "revenue-by-sales-rep-pie",
              title: "Sum of Projected Revenue by Sales Rep",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: false,
                labelColumn: "sales_rep",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "revenue-by-stage-pie",
              title: "Sum of Projected Revenue by Estimate Stage",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: false,
                labelColumn: "stage",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: ["stage"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "pipeline-by-status-bar",
              title: "Company Sales Pipeline by Status",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                labelColumn: "stage",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [],
                  groupBy: ["stage"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "won-estimates-leaderboard-est",
              title: "Won Estimates Leaderboard",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["accepted", "invoiced"] }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "all-open-estimates",
              title: "All Open Estimates",
              size: "full",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: ["client_name", "total_cents", "probability_pct", "sales_rep"],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "top-5-open-estimates",
              title: "Top 5 Open Estimates",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: ["client_name", "total_cents"],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "total_cents",
                  sortDir: "desc",
                  limit: 5,
                },
              },
            },
          ],
        },
        {
          id: "estimates-by-stage",
          name: "Estimates by Stage",
          useDateFilter: false,
          panels: [
            {
              id: "estimates-by-stage-report",
              title: "Estimates by Stage",
              size: "full",
              reportKey: "estimates-by-stage",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "individual-sales-rep",
          name: "Individual Sales Rep",
          useDateFilter: false,
          useRepFilter: true,
          panels: [
            {
              id: "my-open-estimates",
              title: "Open Estimates",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: false,
                useTabRepFilter: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: ["client_name", "total_cents", "probability_pct"],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "my-won-estimates",
              title: "Won Estimates",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: false,
                useTabRepFilter: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: ["client_name", "total_cents"],
                  filters: [{ column: "stage", op: "in", value: ["accepted", "invoiced"] }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "my-current-month-vs-quota",
              title: "Current Month Sales vs Quota",
              size: "half",
              visual: {
                type: "gauge",
                useTabDateRange: false,
                useTabRepFilter: true,
                kpiColumn: "actual_cents",
                budgetColumn: "goal_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_sales_rep_month",
                  columns: ["sales_rep", "goal_cents", "actual_cents"],
                  filters: [],
                  groupBy: [],
                  aggregates: [],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "my-sales-pipeline",
              title: "My Sales Pipeline",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: false,
                useTabRepFilter: true,
                labelColumn: "stage",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: ["stage"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "my-lost-estimates",
              title: "Lost Estimates",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: false,
                useTabRepFilter: true,
                valueColumns: [],
                config: {
                  dataset: "rpt_estimates",
                  columns: ["client_name", "total_cents", "reason"],
                  filters: [{ column: "stage", op: "eq", value: "lost" }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "revenue-by-sales-rep-pie-2",
              title: "Sum of Projected Revenue by Sales Rep",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: false,
                labelColumn: "sales_rep",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_estimates",
                  columns: [],
                  filters: [{ column: "stage", op: "in", value: ["draft", "quote"] }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "invoice-amount-by-sales-rep-pie",
              title: "Sum of Invoice Amount by Sales Rep ($)",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: false,
                labelColumn: "sales_rep",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_invoices",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "void" }],
                  groupBy: ["sales_rep"],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "sales-count-by-sales-rep",
              title: "Sales Count by Sales Rep",
              size: "full",
              visual: {
                type: "crosstab",
                useTabDateRange: false,
                labelColumn: "sales_rep",
                crosstabHeaderColumn: "service_name",
                valueColumns: ["count_all"],
                config: {
                  dataset: "rpt_estimate_line_items",
                  columns: [],
                  filters: [],
                  groupBy: ["sales_rep", "service_name"],
                  aggregates: [{ column: "*", fn: "count" }],
                  sortDir: "asc",
                },
              },
            },
          ],
        },
        {
          id: "sales-commission",
          name: "Sales Commission",
          useDateFilter: false,
          panels: [
            {
              id: "sales-commission-report",
              title: "Sales Commission",
              size: "full",
              reportKey: "sales-commission-export",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
      ],
    },
  },
  {
    key: "ar-overview",
    name: "A/R Overview",
    description: "Outstanding balances, collections, and payment activity.",
    seedable: true,
    config: {
      tabs: [
        {
          id: "overview",
          name: "Overview",
          useDateFilter: true,
          panels: [
            {
              id: "outstanding-balance",
              title: "Outstanding Balance",
              size: "third",
              visual: {
                type: "kpi",
                useTabDateRange: false,
                kpiColumn: "sum_balance_outstanding_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: [],
                  aggregates: [{ column: "balance_outstanding_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "total-invoiced",
              title: "Total Invoiced",
              size: "third",
              visual: {
                type: "kpi",
                useTabDateRange: true,
                kpiColumn: "sum_total_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_invoices",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "void" }],
                  groupBy: [],
                  aggregates: [{ column: "total_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "total-collected",
              title: "Total Collected",
              size: "third",
              visual: {
                type: "kpi",
                useTabDateRange: true,
                kpiColumn: "sum_amount_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_payments",
                  columns: [],
                  filters: [],
                  groupBy: [],
                  aggregates: [{ column: "amount_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "payments-made-today",
              title: "Payments Made Today",
              size: "third",
              visual: {
                type: "kpi",
                useTabDateRange: false,
                relativeDateFilter: "today",
                kpiColumn: "sum_amount_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_payments",
                  columns: [],
                  filters: [],
                  groupBy: [],
                  aggregates: [{ column: "amount_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "payments-made-yesterday",
              title: "Payments Made Yesterday",
              size: "third",
              visual: {
                type: "kpi",
                useTabDateRange: false,
                relativeDateFilter: "yesterday",
                kpiColumn: "sum_amount_cents",
                valueColumns: [],
                config: {
                  dataset: "rpt_payments",
                  columns: [],
                  filters: [],
                  groupBy: [],
                  aggregates: [{ column: "amount_cents", fn: "sum" }],
                  sortDir: "asc",
                },
              },
            },
            {
              id: "invoiced-by-status",
              title: "Invoiced by Status",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                labelColumn: "status",
                valueColumns: ["sum_total_cents"],
                config: {
                  dataset: "rpt_invoices",
                  columns: [],
                  filters: [],
                  groupBy: ["status"],
                  aggregates: [
                    { column: "total_cents", fn: "sum" },
                    { column: "*", fn: "count" },
                  ],
                  sortColumn: "sum_total_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "payments-by-method",
              title: "Payments by Method",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: true,
                labelColumn: "method",
                valueColumns: ["sum_amount_cents"],
                config: {
                  dataset: "rpt_payments",
                  columns: [],
                  filters: [],
                  groupBy: ["method"],
                  aggregates: [{ column: "amount_cents", fn: "sum" }],
                  sortColumn: "sum_amount_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "account-balance-by-type",
              title: "Sum of Account Balance by Account Type",
              size: "half",
              visual: {
                type: "pie",
                useTabDateRange: false,
                labelColumn: "account_type",
                valueColumns: ["sum_balance_outstanding_cents"],
                config: {
                  dataset: "rpt_clients",
                  columns: [],
                  filters: [{ column: "status", op: "neq", value: "lead" }],
                  groupBy: ["account_type"],
                  aggregates: [{ column: "balance_outstanding_cents", fn: "sum" }],
                  sortColumn: "sum_balance_outstanding_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "clients-with-balance",
              title: "Top 10 Clients with a Balance",
              size: "half",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: {
                  dataset: "rpt_clients",
                  columns: ["display_name", "balance_outstanding_cents", "billing_city", "sales_rep"],
                  filters: [{ column: "balance_outstanding_cents", op: "gt", value: 0 }],
                  groupBy: [],
                  aggregates: [],
                  sortColumn: "balance_outstanding_cents",
                  sortDir: "desc",
                  limit: 10,
                },
              },
            },
            {
              id: "invoices-and-payments",
              title: "Invoices and Payments",
              size: "full",
              reportKey: "invoices-and-payments",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "credit-card-charges",
              title: "Credit Card Charges",
              size: "full",
              reportKey: "credit-card-charges",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "open-invoices",
          name: "Open Invoices",
          useDateFilter: false,
          panels: [
            {
              id: "open-invoices-report",
              title: "Open Invoices",
              size: "full",
              reportKey: "invoices-with-balances",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "aging-report-snapshot",
          name: "Aging Report Snapshot",
          useDateFilter: false,
          panels: [
            {
              id: "aging-report-snapshot-report",
              title: "Aging Report Snapshot",
              size: "full",
              reportKey: "ar-aging-snapshot",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "ar-aging-report",
          name: "A/R Aging Report",
          useDateFilter: false,
          panels: [
            {
              id: "ar-aging-report-report",
              title: "A/R Aging Report",
              size: "full",
              reportKey: "ar-aging",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
        {
          id: "payments-reports",
          name: "Payments Reports",
          useDateFilter: false,
          panels: [
            {
              id: "unapplied-payments-report",
              title: "Unapplied Payments",
              size: "third",
              reportKey: "unapplied-payments",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "pre-payments-report",
              title: "Pre-Payments",
              size: "third",
              reportKey: "pre-payments",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
            {
              id: "payment-audit-summary-report",
              title: "Payment Audit Summary",
              size: "third",
              reportKey: "payment-audit-summary",
              visual: {
                type: "table",
                useTabDateRange: false,
                valueColumns: [],
                config: { dataset: "unused", columns: [], filters: [], groupBy: [], aggregates: [], sortDir: "asc" },
              },
            },
          ],
        },
      ],
    },
  },
  {
    key: "crew-production-avb",
    name: "Crew Production (AvB)",
    description: "Actual vs. budgeted hours and revenue per man-hour by crew.",
    config: {
      tabs: [
        {
          id: "avb",
          name: "AvB",
          useDateFilter: true,
          panels: [
            {
              id: "rev-per-man-hr-by-crew",
              title: "Actual Revenue / Man Hour by Crew",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                labelColumn: "crew_name",
                valueColumns: ["avg_rev_per_man_hr_cents"],
                config: {
                  dataset: "rpt_job_visits",
                  columns: [],
                  filters: [],
                  groupBy: ["crew_name"],
                  aggregates: [{ column: "rev_per_man_hr_cents", fn: "avg" }],
                  sortColumn: "avg_rev_per_man_hr_cents",
                  sortDir: "desc",
                },
              },
            },
            {
              id: "variance-hours-by-crew",
              title: "Actual Time Variance (Hours) by Crew",
              size: "half",
              visual: {
                type: "bar",
                useTabDateRange: true,
                labelColumn: "crew_name",
                valueColumns: ["sum_variance_hours"],
                config: {
                  dataset: "rpt_job_visits",
                  columns: [],
                  filters: [],
                  groupBy: ["crew_name"],
                  aggregates: [{ column: "variance_hours", fn: "sum" }],
                  sortColumn: "sum_variance_hours",
                  sortDir: "desc",
                },
              },
            },
          ],
        },
      ],
    },
  },
];

export function getDashboardTemplate(key: string | undefined): DashboardTemplate | undefined {
  if (!key) return undefined;
  return DASHBOARD_TEMPLATES.find((t) => t.key === key);
}

export function getSeedableDashboardTemplates(): DashboardTemplate[] {
  return DASHBOARD_TEMPLATES.filter((t) => t.seedable);
}
