-- PM compliance scored against each schedule's calendar, not just the work
-- orders that happen to exist. Supersedes v_pm_work_order_outcomes from
-- 20260927100000_cmms_warranty_uptime_metrics.sql.
--
-- PM work orders are generated by hand, so a cycle nobody generated used to
-- leave no trace and couldn't count against anyone. Three sources of "PM
-- unit" now feed one view, v_pm_outcomes:
--
--   1. Work orders: PM-schedule WOs (as before) plus meter-triggered WOs —
--      those whose automation is a meter_threshold rule. A meter PM comes due
--      7 days after the meter tripped (the request's creation, or the WO's
--      own when the automation created it directly).
--   2. Cycles never generated ("not_generated", counts as missed):
--      a. Live: every cycle from an active schedule's next_due_date that has
--         already passed. Generating the batch turns the first of them into
--         a real (late) WO.
--      b. History: gaps between consecutive batches. generate-wo advances the
--         schedule one interval from the day it runs, so a late batch doesn't
--         shift the calendar; a gap only means missed cycles when the next
--         batch came at least two intervals later (weekly: 9/2 → 9/16 = one
--         missed, 9/2 → 9/10 = one late batch, none missed). Assets come from
--         the batch before the gap.
--      c. Meter requests still unconverted 7 days after the meter tripped.
--   3. Existing meter-triggered WOs are retagged wo_type = 'preventive' so the
--      cost split counts them as PM (request conversion hard-coded
--      'reactive').

-- ── cycle arithmetic ────────────────────────────────────────────────────────
-- Stepping from the start date each time (not from the previous step) keeps
-- month-end dates from drifting: Jan 31 + 1 month = Feb 28, + 2 months = Mar 31.

create or replace function public.pm_cycle_date(p_start date, p_frequency text, p_n integer)
returns date
language sql
immutable
set search_path to 'public'
as $$
  select case p_frequency
    when 'daily'     then p_start + p_n
    when 'weekly'    then p_start + 7 * p_n
    when 'monthly'   then (p_start + make_interval(months => p_n))::date
    when 'quarterly' then (p_start + make_interval(months => 3 * p_n))::date
    when 'annual'    then (p_start + make_interval(months => 12 * p_n))::date
  end;
$$;

-- The shortest a cycle of each frequency can be; bounds generate_series.
create or replace function public.pm_cycle_min_days(p_frequency text)
returns integer
language sql
immutable
set search_path to 'public'
as $$
  select case p_frequency
    when 'daily' then 1 when 'weekly' then 7 when 'monthly' then 28
    when 'quarterly' then 89 when 'annual' then 365
  end;
$$;

revoke all on function public.pm_cycle_date(date, text, integer) from public, anon;
revoke all on function public.pm_cycle_min_days(text) from public, anon;
grant execute on function public.pm_cycle_date(date, text, integer) to authenticated;
grant execute on function public.pm_cycle_min_days(text) to authenticated;

-- ── retag existing meter-triggered WOs as preventive ────────────────────────
-- Same trigger pause as the completed_at backfill: a retag of history is not
-- an edit anyone made, and must not stamp updated_at.

alter table public.work_orders disable trigger trg_audit_work_orders;
alter table public.work_orders disable trigger trg_work_orders_updated_at;

update public.work_orders w
   set wo_type = 'preventive'
  from public.automations a
 where a.id = w.automation_id
   and a.trigger_type = 'meter_threshold'
   and w.wo_type is distinct from 'preventive';

alter table public.work_orders enable trigger trg_audit_work_orders;
alter table public.work_orders enable trigger trg_work_orders_updated_at;

-- ── v_pm_outcomes ───────────────────────────────────────────────────────────

drop function if exists public.cmms_asset_metrics(integer, uuid);
drop view if exists public.v_pm_work_order_outcomes;

create or replace view public.v_pm_outcomes
with (security_invoker = on) as
with wo_units as (
  -- PM-schedule work orders, excluding multi-asset batch parents (their
  -- sub-WOs are the units).
  select 'schedule'::text                         as source,
         w.pm_schedule_id                         as program_id,
         s.title                                  as program_name,
         w.id                                     as work_order_id,
         w.work_order_number,
         w.org_id, w.asset_id, w.asset_name, w.status, w.due_date,
         coalesce(w.due_date, (w.created_at at time zone public.org_timezone(w.org_id))::date) as due_on,
         w.due_date is not null                   as has_due,
         w.completed_at
    from public.work_orders w
    left join public.pm_schedules s on s.id = w.pm_schedule_id
   where w.deleted_at is null
     and w.pm_schedule_id is not null
     and not exists (select 1 from public.work_orders c
                      where c.parent_work_order_id = w.id and c.deleted_at is null)
  union all
  -- Meter-triggered work orders: due 7 days after the meter tripped.
  select 'meter', a.id, a.name, w.id, w.work_order_number,
         w.org_id, w.asset_id, w.asset_name, w.status, w.due_date,
         coalesce(w.due_date,
                  (coalesce(r.created_at, w.created_at) at time zone public.org_timezone(w.org_id))::date + 7),
         true,
         w.completed_at
    from public.work_orders w
    join public.automations a on a.id = w.automation_id and a.trigger_type = 'meter_threshold'
    left join lateral (
      select mr.created_at from public.maintenance_requests mr
       where mr.linked_work_order_id = w.id and mr.deleted_at is null
       order by mr.created_at limit 1
    ) r on true
   where w.deleted_at is null
     and w.pm_schedule_id is null
),
batches as (
  select w.id, w.org_id, w.pm_schedule_id, s.frequency,
         coalesce(w.due_date, (w.created_at at time zone public.org_timezone(w.org_id))::date) as cycle_on,
         lead(coalesce(w.due_date, (w.created_at at time zone public.org_timezone(w.org_id))::date))
           over (partition by w.pm_schedule_id
                 order by coalesce(w.due_date, (w.created_at at time zone public.org_timezone(w.org_id))::date), w.created_at) as next_on
    from public.work_orders w
    join public.pm_schedules s on s.id = w.pm_schedule_id
   where w.deleted_at is null
     and w.pm_schedule_id is not null
     and w.parent_work_order_id is null
),
gap_units as (
  select b.org_id, b.pm_schedule_id, public.pm_cycle_date(b.cycle_on, b.frequency, k) as due_on,
         u.asset_id, u.asset_name
    from batches b
   cross join lateral generate_series(1, greatest(0, (b.next_on - b.cycle_on) / public.pm_cycle_min_days(b.frequency))) k
   cross join lateral (
     select c.asset_id, c.asset_name from public.work_orders c
      where c.parent_work_order_id = b.id and c.deleted_at is null and c.asset_id is not null
     union
     select w.asset_id, w.asset_name from public.work_orders w
      where w.id = b.id and w.asset_id is not null
   ) u
   where b.next_on is not null
     and public.pm_cycle_date(b.cycle_on, b.frequency, k + 1) <= b.next_on
),
trail_units as (
  select s.org_id, s.id as pm_schedule_id, public.pm_cycle_date(s.next_due_date, s.frequency, k) as due_on,
         sa.asset_id, coalesce(a.name, v.name, sa.asset_name) as asset_name
    from public.pm_schedules s
   cross join lateral generate_series(0, (public.org_today(s.org_id) - s.next_due_date) / public.pm_cycle_min_days(s.frequency)) k
    join public.pm_schedule_assets sa on sa.pm_schedule_id = s.id and sa.deleted_at is null
    left join public.assets a   on a.id = sa.asset_id and a.deleted_at is null and a.status <> 'disposed'
    left join public.vehicles v on v.id = sa.asset_id and v.deleted_at is null and v.status <> 'disposed'
   where s.deleted_at is null
     and s.is_active
     and s.next_due_date is not null
     and s.next_due_date < public.org_today(s.org_id)
     and public.pm_cycle_date(s.next_due_date, s.frequency, k) < public.org_today(s.org_id)
     and (a.id is not null or v.id is not null)
)
select source, program_id, program_name, work_order_id, work_order_number, org_id, asset_id, asset_name,
       status, due_date, due_on, completed_at,
       (completed_at at time zone public.org_timezone(org_id))::date as completed_on,
       case
         when status = 'done' and has_due
              and (completed_at at time zone public.org_timezone(org_id))::date > due_on then 'late'
         when status = 'done' and has_due                                       then 'on_time'
         when status = 'done'                                                   then 'completed'
         when status = 'skipped'                                                then 'skipped'
         when has_due and due_on < public.org_today(org_id)                     then 'overdue'
         else 'pending'
       end as outcome
  from wo_units
union all
select 'schedule', g.pm_schedule_id, s.title, null::uuid, null::text, g.org_id, g.asset_id, g.asset_name,
       null::text, null::date, g.due_on, null::timestamptz, null::date, 'not_generated'
  from gap_units g
  join public.pm_schedules s on s.id = g.pm_schedule_id
union all
select 'schedule', t.pm_schedule_id, s.title, null::uuid, null::text, t.org_id, t.asset_id, t.asset_name,
       null::text, null::date, t.due_on, null::timestamptz, null::date, 'not_generated'
  from trail_units t
  join public.pm_schedules s on s.id = t.pm_schedule_id
union all
select 'meter', a.id, a.name, null::uuid, null::text, r.org_id, r.asset_id, r.asset_name,
       r.status, null::date,
       (r.created_at at time zone public.org_timezone(r.org_id))::date + 7,
       null::timestamptz, null::date, 'not_generated'
  from public.maintenance_requests r
  join public.automations a on a.id = r.automation_id and a.trigger_type = 'meter_threshold'
 where r.deleted_at is null
   and r.linked_work_order_id is null
   and r.status in ('open', 'in_review', 'approved')
   and (r.created_at at time zone public.org_timezone(r.org_id))::date + 7 < public.org_today(r.org_id);

comment on view public.v_pm_outcomes is
  'One row per PM unit — a scheduled or meter-triggered PM on one asset — with its compliance outcome, including cycles that were never generated (outcome not_generated, work_order_id null). security_invoker, so RLS applies.';

revoke all on public.v_pm_outcomes from anon;
grant select on public.v_pm_outcomes to authenticated;

-- ── cmms_asset_metrics: read v_pm_outcomes, report not_generated ────────────

create or replace function public.cmms_asset_metrics(
  p_window_days integer default 90,
  p_asset_id    uuid    default null
)
returns table (
  entity_type           text,
  asset_id              uuid,
  name                  text,
  asset_tag             text,
  asset_type            text,
  status                text,
  location              text,
  purchase_price        integer,
  warranty_end_date     date,
  window_days           integer,
  uptime_pct            numeric,
  in_service_hours      numeric,
  downtime_hours        numeric,
  downtime_events       integer,
  mttr_hours            numeric,
  down_since            timestamptz,
  wo_count              integer,
  open_wo_count         integer,
  cost_12mo_cents       bigint,
  pm_cost_12mo_cents    bigint,
  cost_lifetime_cents   bigint,
  pm_cost_lifetime_cents bigint,
  pm_due                integer,
  pm_completed          integer,
  pm_on_time            integer,
  pm_late               integer,
  pm_skipped            integer,
  pm_overdue            integer,
  pm_not_generated      integer
)
language sql
stable
security invoker
set search_path to 'public'
as $$
  with params as (
    select now() as t_end,
           now() - make_interval(days => greatest(1, least(coalesce(p_window_days, 90), 3650))) as t_start,
           greatest(1, least(coalesce(p_window_days, 90), 3650)) as days
  ),
  units as (
    select 'asset'::text as entity_type, a.id, a.org_id, a.name, a.asset_tag, a.asset_type, a.status,
           a.location, a.purchase_price, a.warranty_end_date
      from assets a
     where a.deleted_at is null and (p_asset_id is null or a.id = p_asset_id)
    union all
    select 'vehicle', v.id, v.org_id, v.name, v.asset_tag, v.asset_type, v.status,
           v.location, v.purchase_price, v.warranty_end_date
      from vehicles v
     where v.deleted_at is null and (p_asset_id is null or v.id = p_asset_id)
  ),
  periods as (
    select h.entity_type, h.asset_id, h.status, h.started_at, h.ended_at,
           greatest(h.started_at, p.t_start)             as s,
           least(coalesce(h.ended_at, p.t_end), p.t_end) as e,
           h.status in ('in_shop', 'out_of_service')     as is_down,
           p.t_start
      from asset_status_history h
      join units u on u.id = h.asset_id and u.entity_type = h.entity_type
     cross join params p
     where h.deleted_at is null
       and coalesce(h.ended_at, p.t_end) > p.t_start
  ),
  uptime as (
    select entity_type, asset_id,
           coalesce(sum(extract(epoch from (e - s))) filter (where is_down and e > s), 0)            as down_secs,
           coalesce(sum(extract(epoch from (e - s))) filter (where status = 'active' and e > s), 0)  as active_secs,
           count(*) filter (where is_down and started_at >= t_start)                                  as events,
           avg(extract(epoch from (ended_at - started_at)))
             filter (where is_down and ended_at is not null and started_at >= t_start)               as mttr_secs,
           max(started_at) filter (where is_down and ended_at is null)                               as down_since
      from periods
     group by entity_type, asset_id
  ),
  wos as (
    select w.id, w.asset_id, w.status, w.created_at,
           coalesce(w.completed_at, w.created_at) as cost_at,
           (w.wo_type = 'preventive' or w.pm_schedule_id is not null) as is_pm
      from work_orders w
     where w.deleted_at is null
       and w.asset_id in (select id from units)
  ),
  wo_cost as (
    select wos.id,
           coalesce((select sum(p.quantity::bigint * p.unit_cost) from wo_parts p
                      where p.work_order_id = wos.id and p.deleted_at is null), 0)
         + coalesce((select sum(round(l.hours * l.hourly_rate))::bigint from wo_labor_entries l
                      where l.work_order_id = wos.id and l.deleted_at is null), 0)
         + coalesce((select sum(c.cost)::bigint from wo_vendor_charges c
                      where c.work_order_id = wos.id and c.deleted_at is null), 0) as cents
      from wos
     where wos.status <> 'skipped'
  ),
  wo_rollup as (
    select wos.asset_id,
           count(*) filter (where wos.created_at >= p.t_start)                           as wo_count,
           count(*) filter (where wos.status not in ('done', 'skipped'))                  as open_count,
           coalesce(sum(c.cents) filter (where wos.cost_at >= p.t_end - interval '12 months'), 0)               as c12,
           coalesce(sum(c.cents) filter (where wos.is_pm and wos.cost_at >= p.t_end - interval '12 months'), 0) as pm_c12,
           coalesce(sum(c.cents), 0)                                                      as c_life,
           coalesce(sum(c.cents) filter (where wos.is_pm), 0)                             as pm_c_life
      from wos
      left join wo_cost c on c.id = wos.id
     cross join params p
     group by wos.asset_id
  ),
  pm as (
    select o.asset_id,
           count(*) filter (where o.outcome in ('on_time', 'late', 'completed'))                                          as completed,
           count(*) filter (where o.outcome in ('on_time', 'late', 'completed', 'skipped', 'overdue', 'not_generated'))   as due,
           count(*) filter (where o.outcome = 'on_time')                                                                  as on_time,
           count(*) filter (where o.outcome = 'late')                                                                     as late,
           count(*) filter (where o.outcome = 'skipped')                                                                  as skipped,
           count(*) filter (where o.outcome = 'overdue')                                                                  as overdue,
           count(*) filter (where o.outcome = 'not_generated')                                                            as not_generated
      from v_pm_outcomes o
     cross join params p
     where o.asset_id in (select id from units)
       and o.due_on >= (p.t_start at time zone org_timezone(o.org_id))::date
     group by o.asset_id
  )
  select u.entity_type, u.id, u.name, u.asset_tag, u.asset_type, u.status, u.location,
         u.purchase_price, u.warranty_end_date,
         (select days from params)::integer,
         case when coalesce(up.active_secs, 0) + coalesce(up.down_secs, 0) > 0
              then round(100.0 * up.active_secs / (up.active_secs + up.down_secs), 1) end,
         round((coalesce(up.active_secs, 0) + coalesce(up.down_secs, 0)) / 3600.0, 1),
         round(coalesce(up.down_secs, 0) / 3600.0, 1),
         coalesce(up.events, 0)::integer,
         round(up.mttr_secs / 3600.0, 1),
         up.down_since,
         coalesce(wr.wo_count, 0)::integer,
         coalesce(wr.open_count, 0)::integer,
         coalesce(wr.c12, 0)::bigint,
         coalesce(wr.pm_c12, 0)::bigint,
         coalesce(wr.c_life, 0)::bigint,
         coalesce(wr.pm_c_life, 0)::bigint,
         coalesce(pm.due, 0)::integer,
         coalesce(pm.completed, 0)::integer,
         coalesce(pm.on_time, 0)::integer,
         coalesce(pm.late, 0)::integer,
         coalesce(pm.skipped, 0)::integer,
         coalesce(pm.overdue, 0)::integer,
         coalesce(pm.not_generated, 0)::integer
    from units u
    left join uptime    up on up.asset_id = u.id and up.entity_type = u.entity_type
    left join wo_rollup wr on wr.asset_id = u.id
    left join pm           on pm.asset_id = u.id
   order by u.name;
$$;

comment on function public.cmms_asset_metrics(integer, uuid) is
  'Per-asset/vehicle uptime, downtime, MTTR, WO counts, 12-month + lifetime maintenance cost (cents), and PM compliance (from v_pm_outcomes, incl. never-generated cycles) over the trailing p_window_days. SECURITY INVOKER — RLS scopes it to the caller''s org.';

revoke all on function public.cmms_asset_metrics(integer, uuid) from public, anon;
grant execute on function public.cmms_asset_metrics(integer, uuid) to authenticated;

notify pgrst, 'reload schema';
